GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/4

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Rest Boy",
  "number": "420-58247-92"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "89234-23423"
}

###
PUT http://localhost:3001/api/persons/64262f9d79c85744791fe81f
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "239-2342-85"
}

###
POST https://phonebook-h4o7.onrender.com/api/persons
Content-Type: application/json

{
  "name": "Rest Boy",
  "number": "420-58247-92"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Re",
  "number": "420-582-92"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Red",
  "number": "42-58234234-234"
}

